extends: existence
level: suggestion
message: "Do not use transitive verb constructions like '%s' to grant abilities to inanimate objects. Whenever possible, use direct, user-focused sentences where the subject of the sentence performs the action."
ignorecase: true
tokens:
  - '(allows?|enables?|lets?|permits?)\s(you|customers|the customer|the user|users)'
